version: '3.8'
services:
  # Development services
  app_dev:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: umbrella/Dockerfile
      target: dev
    container_name: portfolio_dev
    ports:
      - "4000:4000"
    volumes:
      - ./umbrella:/app
    working_dir: /app

  nginx_dev:
    profiles: ["dev"]
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app_dev

  # Production services
  app:
    profiles: ["prod"]
    build:
      context: .
      dockerfile: umbrella/Dockerfile
      target: prod
    container_name: portfolio_prod
    env_file:
      - .env
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      MIX_ENV: prod

  nginx:
    profiles: ["prod"]
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./prod/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
