version: '3.8'

services:
  phoenix:
    build:
      context: ./umbrella
      dockerfile: Dockerfile
    container_name: phoenix_app
    ports:
      - "4000:4000"
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - phoenix
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
