version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: umbrella/Dockerfile.prod
    container_name: portfolio_prod
    env_file:
      - .env
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      MIX_ENV: prod

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
