version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: umbrella/Dockerfile.dev
    container_name: portfolio_dev
    env_file:
      - .env
    ports:
      - "4000:4000"
    volumes:
      - ./umbrella:/app
    working_dir: /app
    environment:
      MIX_ENV: "dev"
    command: ["mix", "phx.server"]

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
