services:
  db:
    image: postgres:16
    container_name: portfolio_db
    profiles: ["dev", "prod"]
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  # Development services
  app_dev:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: umbrella/Dockerfile
      target: dev
    container_name: portfolio_dev
    env_file:
      - .env
    ports:
      - "4000:4000"
      - "4001:4000"
    volumes:
      - ./umbrella:/app
    working_dir: /app
    environment:
      MIX_ENV: dev
      DATABASE_URL: ${DATABASE_URL_DEV}
    depends_on:
      - db

  nginx_dev:
    profiles: ["dev"]
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app_dev

  # Production services
  app:
    profiles: ["prod"]
    build:
      context: .
      dockerfile: umbrella/Dockerfile
      target: prod
    container_name: portfolio_prod
    env_file:
      - .env
    ports:
      - "4000:4000"
      - "4001:4000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
    - db

  nginx:
    profiles: ["prod"]
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./prod/nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db_data:
