version: '3.8'

services:
  app:
    image: ghcr.io/frick-eldy/portfolio:latest
    container_name: portfolio_app
    restart: always
    env_file:
      - .env
    ports:
      - "4000:4000"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
