version: '3.8'

services:
  app:
    image: ghcr.io/frick-eldy/portfolio:latest
    container_name: portfolio_app
    restart: always
    env_file:
      - .env
    ports:
      - "4000:4000"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    depends_on:
      - app

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    restart: always
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    depends_on:
      - nginx

volumes:
  certbot-etc:
  certbot-www:
