
services:
  db:
    image: postgres:16
    container_name: portfolio_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    image: ghcr.io/frick-eldy/portfolio:latest
    container_name: portfolio_app
    restart: always
    env_file:
      - .env
    ports:
      - "4000:4000"
      - "4001:4000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    depends_on:
      - app

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    restart: always
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    depends_on:
      - nginx

volumes:
  db_data:
  certbot-etc:
  certbot-www:
