name: Continuous Deployment

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SAKURA_SSH_KEY }}

      - name: Setup SSH Known Hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SAKURA_HOST_KEY }}" > ~/.ssh/known_hosts

      - name: Deploy to Sakura Internet
        run: |
          ssh ${{ secrets.SAKURA_USER }}@${{ secrets.SAKURA_HOST }} << 'EOF'
          set -e
          cd /home/ubuntu/portfolio
          echo "Pulling latest code..."
          git pull origin main
          echo "Building and starting Docker containers..."
          docker compose --profile prod up -d --build
          echo "Deployment finished."
          EOF
