name: CI

on:
  pull_request:
    branches:
      - main

jobs:        
  compile:
    name: Check Compile
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.18.3'
        otp-version: '27.0'
    - name: elixir-setup
      run: |
        cd $GITHUB_WORKSPACE/umbrella
        mix local.hex --force
        mix local.rebar --force
        mix deps.get
        mix compile --warnings-as-errors

  format:
    name: Check Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18.3'
          otp-version: '27.0'
      - name: elixir-setup
        run: |
          cd $GITHUB_WORKSPACE/umbrella
          mix local.hex --force
          mix local.rebar --force
          mix deps.get
          mix format --check-formatted

  credo:
    name: Check Credo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18.3'
          otp-version: '27.0'
      - name: elixir-setup
        run: |
          cd $GITHUB_WORKSPACE/umbrella
          mix local.hex --force
          mix local.rebar --force
          mix deps.get
          mix credo --strict

  test:
    name: Check Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      MIX_ENV: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18.3'
          otp-version: '27.0'
      - name: elixir-setup
        run: |
          cd $GITHUB_WORKSPACE/umbrella
          mix local.hex --force
          mix local.rebar --force
          mix deps.get
          mix compile
          mix ecto.create
          mix ecto.migrate
          mix test

  dialyzer:
    name: Check Dialyzer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18.3'
          otp-version: '27.0'

      - name: Cache PLT
        uses: actions/cache@v3
        with:
          path: |
            _build
            priv/plts
          key: dialyzer-${{ runner.os }}-${{ steps.setup-beam.outputs.elixir-version }}-${{ steps.setup-beam.outputs.otp-version }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            dialyzer-${{ runner.os }}-${{ steps.setup-beam.outputs.elixir-version }}-${{ steps.setup-beam.outputs.otp-version }}-
      - name: dialyzer
        run: |
          cd $GITHUB_WORKSPACE/umbrella
          mix local.hex --force
          mix local.rebar --force
          mix deps.get
          mix dialyzer --plt
          mix dialyzer --halt-exit-status
