name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18.3'
          otp-version: '27.0'

      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE/umbrella
          mix local.hex --force
          mix local.rebar --force
          mix deps.get

      - name: Run Tests
        run: |
          cd $GITHUB_WORKSPACE/umbrella
          mix test
